# Generated by Django 2.0 on 2018-01-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='classification',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='result',
            name='petal_length',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='petal_width',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
